### ISSUE TITLE
[Bug] Overall Device connection lost after 80 - 85min

### ISSUE THREAD

**Issue by MedTechCD** [incyclist/desktop#88]
Used a loop video with a basic simple workout (5min WU - 80min Steady - 5min CD) and lost all device connection (HR - Power (Power Meter) - Speed (Smarttrainer)) on 2 consecutive rides. Device connections during the ride suddenly changed icon first to Red/Yellow then Red X (could be slightly different). All values are sticky at the last one recorded except elevation which comes from the gpx. But the controllable continues the workout and managed my cooldown correctly. So looks like only the sensor reading fails while control remains.
Everything is connected through ANT+, other protocols are disabled. Smarttrainer as controllable & speed sensor, Favero pedals as Power & Cadence sensor and Polar H10 as HR.
I'm wondering if there's some sort of time out kicking in because the first one took around 5 min extra prep time while connected compared to the second one. It might be just an impression but I think with same start routine, it would have been almost exactly at the same point in the ride (time-wise).
If you need files, screenshots or logs, just ask.
I will continue to investigate and try to narrow down.

**Comment by gdoumen** [comment]
PLease provide your UUID (See: Settings->Support).

**Comment by MedTechCD** [comment]
Here's the UUID.
9b92856b-1393-420d-a8e7-78b003dcb720

My trainer provides Power, Speed and Cadence, but I prefer Power and cadence from my pedals.
Would it make a difference if I paired my pedals in BLE and keep HR/Controllable on ANT+? Would that reduce the risk of channel collisions?
BTW: Yesterday I noticed a popup signalling another rider in the neighbourhood. Is that WIP?

**Comment by gdoumen** [comment]
I can see in the logs that the three devices simply stopped sending data, so I assume it's an issue on the ANT+ stick. 

However, in previous versions of the UI, I was detecting this situation ("all devices on the same stick are not sending data") and restarting the whole ANT+ interface. This was not happening in your situation. I need to analyse what is causing this. So it seems to be a regression

>Would that reduce the risk of channel collisions?
It definitively would - although in this specific case, it was not a channel collision; it was just the ANT-Stick not sending any data anymore

>BTW: Yesterday I noticed a popup signalling another rider in the neighbourhood. Is that WIP?
No it's not WIP. It's a feature. If two or more riders are on the same route, you can see the position/speed/power of the other riders. However, there is not yet too much traffic in the app. So the likelyhood to face this is still quite low. But there are some users, who do planned group rides ( align over mail/whatsapp/... on a specific route and start time)

**Comment by MedTechCD** [comment]
Then I guess it must be some sort of Energy saving setting on USB and/or ANT stick. The sensors were still working because I dual record with my head device. And as I said, the uptime in both cases was very similar.
I will check it out and come back to you. Don't waste any time on it now, I have the full data from my Edge computer.

**Comment by gdoumen** [comment]
There was another user (on a different channel) reporting the same issue. So I definitively need to investigate. 

This is something, I had observed ~1-1.5years ago and it seems to have been fixed with the interface restart (at least it had not popped up until then, although I had a tester who could consistemtly reproduce the issue). 

I guess with one of my latest modifications on the interface code, I might have caused a regression

**Comment by MedTechCD** [comment]
I found a setting in Power settings called 'USB Selective Suspend' which was enabled. I have disabled that now and will test this evening to see if it influences.
Since I'm not touching anything on my laptop while riding, it could kick-in after a while?

**Comment by MedTechCD** [comment]
The USB suspend disable does not solve the problem. Same thing occurred after ~83min.
And I manipulated the laptop by zooming the map after 30 some minutes. Looks like the problem is in the code.

**Comment by gdoumen** [comment]
I think I found the issue and should have fixed it. PLease retest.

The devices probaby still will show up amber/red after 80mins, but should then recover (~5-10s after they became red)
During this phase of restart, the app will use the previous values ( speed and power).

**Comment by MedTechCD** [comment]
Exactly what you say around the 82min mark. Short interruption in sensor reading and trainer control, recovered in a couple of seconds.
Thanks,
